
# ---- BUILD IMAGE ----
build:
  stage: build
  extends: .base_docker_job
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -f Dockerfile.prod -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "dev"'